crmserver/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('reports/', include('reports.urls')),
    path('', include('marketingemails.urls')),
    path('marketingtexts/', include('marketingtexts.urls')),
]

reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),

    # EMAIL REPORTS
    path('campaigns/', views.campaigns, name='campaigns'),
    path('campaigns/<str:campaign_id>', views.single_campaign_report, name='single_campaign_report'),
    path('campaign_series/', views.campaign_series, name='campaign_series'),
    path('campaign_series/<str:parent_campaign_id>', views.single_campaign_series, name='single_campaign_series'),

    # SMS REPORTS
    path('sms_campaigns/', views.sms_campaigns, name='sms_campaigns'),
    path('sms_campaigns/<str:campaign_id>', views.single_sms_campaign_report, name='single_sms_campaign_report'),
    path('sms_campaign_series/', views.sms_campaign_series, name='sms_campaign_series'),
    path('sms_campaign_series/<str:parent_campaign_id>', views.single_sms_campaign_series, name='single_sms_campaign_series'),

    # USER REPORTS
    path('audience/', views.audience, name='audience'),
    path('audience/<str:user_id>', views.single_user_view, name='single_user_report'),
    path('micromarkets/', views.micromarkets, name='micromarkets'),
    path('micromarkets/<str:subregion>', views.single_micromarket, name='single_micromarket'),
]

reports/models.py
from django.db import models

# Create your models here.

reports/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.core.mail import get_connection, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.timezone import now as timezone_now

from marketingemails.models import User, UserStatus, Campaigns
from .utils import users_interactions_single_campaign, users_interactions_all_campaigns, user_hit_rates, user_sms_hit_rates

from marketingtexts.models import SMSCampaign


def index(request):
    return render(request, 'reports/index.html')


def campaigns(request):
    '''
    Render list of all the campaigns ever sent
    '''
    successful_campaigns = Campaigns.objects.all()
    context = {
        'campaigns': successful_campaigns
    }
    return render(request, 'reports/campaigns.html', {'campaigns': successful_campaigns})


def single_campaign_report(request, campaign_id):
    '''
    Render reports for a single campaign
    '''
    campaign = get_object_or_404(Campaigns, pk=campaign_id)
    
    # Get all users and filter the ones for this campaign
    all_users = User.objects.all()
    users_for_campaign, campaign_interactions = users_interactions_single_campaign(all_users, campaign_id)
    extras = {
        'campaign_interactions': campaign_interactions
    }

    return render(request, 'reports/campaign_report.html', 
        {'users': users_for_campaign, 'campaign': campaign, 'extras': extras})

    
def audience(request):
    '''
    Renders the HTML view for every user present in the database alognside their interactions
    '''
    users = User.objects.all()
    users_status = UserStatus.objects.all()
    users_interaction = users_interactions_all_campaigns(users)
    return render(request, 'reports/audience.html', {'users': users_interaction})


def single_user_view(request, user_id):
    '''
    Renders view for a single user with the campaigns they have participated in
    '''
    user = get_object_or_404(User, pk=user_id)
    user_status = get_object_or_404(UserStatus, pk=user_id)
    user_campaign_dict = {}
    for campaign_id in user.participated_campaigns:
        campaign = get_object_or_404(Campaigns, pk=campaign_id)
        campaign_dict = {
            'name': campaign.name,
            'email_opens': user_status.email_opens.get(campaign_id),
            'link_opens': user_status.link_opens.get(campaign_id)
        } 
        user_campaign_dict[campaign_id] = campaign_dict    

    return render(request, 'reports/single_user.html', {'user': user, 'campaigns': user_campaign_dict})


def micromarkets(request):
    '''
    Renders view for each city and it's interactions.
    '''
    users = User.objects.all()
    user_interactions = users_interactions_all_campaigns(users)
    city_map, subregion_map, subregion_to_city = {}, {}, {}
    
    for interaction in user_interactions:
        if interaction['location_of_interest'] not in subregion_to_city:
            subregion_to_city[interaction['location_of_interest']] = interaction['city']

        if interaction['location_of_interest'] in subregion_map:
            subregion_map[interaction['location_of_interest']] += interaction['total_interactions']
        else:
            subregion_map[interaction['location_of_interest']] = interaction['total_interactions']

        if interaction['city'] in city_map:
            city_map[interaction['city']] += interaction['total_interactions']
        else:
            city_map[interaction['city']] = interaction['total_interactions']

    final_subregions = []
    for k, v in subregion_map.items():
        final_subregions.append({'subregion': k, 'city': subregion_to_city.get(k, 'NULL'), 'impressions': v})

    return render(request, 'reports/micromarkets.html', {'cities': city_map, 'subregions': final_subregions})
        

def single_micromarket(request, subregion):
    '''
    Renders view for single micromarket and the users that have participated in it.
    '''
    users_for_location = User.objects.filter(location_of_interest=subregion)
    users_interaction = users_interactions_all_campaigns(users_for_location)
    return render(request, 'reports/single_location.html', {'users': users_interaction, 'subregion': subregion})


def campaign_series(request):
    '''
    Campaign series is a series of marketing campaigns that are dispatched automatically, these
    campaigns are listed under this view and further information is displayed here.
    '''
    parent_campaigns = Campaigns.objects.exclude(future_campaigns='').filter(parent_campaigns='')
    context = {
        'campaigns': parent_campaigns
    }
    return render(request, 'reports/parent_campaigns.html', {'campaigns': parent_campaigns})


def single_campaign_series(request, parent_campaign_id):
    '''
    A single campaign series view displays information of the campaigns within this series alongwith the 
    dates and status of the campaigns
    '''
    parent_campaign = get_object_or_404(Campaigns, pk=parent_campaign_id)
    child_campaign_ids = parent_campaign.future_campaigns

    campaigns_sent = []
    campaigns_pending = []
    for id in child_campaign_ids:
        child = Campaigns.objects.filter(pk=id, launch_datetime__lte = timezone_now())
        if child:
            campaigns_sent.append(Campaigns.objects.get(pk=id))
        else:
            campaigns_pending.append(Campaigns.objects.get(pk=id))
    
    campaigns_sent.append(parent_campaign)
    if campaigns_sent:
        parent_campaign_user_ids = parent_campaign.audience
        parent_campaign_users = User.objects.in_bulk(parent_campaign_user_ids)
        if parent_campaign_users:
            parent_campaign_users = list(parent_campaign_users.values())

        hitrate_percentages = user_hit_rates(parent_campaign_users, campaigns_sent)
        return render(request, 'reports/single_campaign_series.html', {
            'hitrates': hitrate_percentages, 
            'campaign': parent_campaign, 
            'childs_sent': campaigns_sent,
            'childs_pending': campaigns_pending})
    else:
        return render(request, 'reports/null_series.html', {'childs_pending': campaigns_pending})


def sms_campaigns(request):
    '''
    This view and below defined views are analogous to the email campaign views only for the SMS views.
    '''
    successful_campaigns = SMSCampaign.objects.all()
    context = {
        'campaigns': successful_campaigns
    }
    return render(request, 'reports/sms_campaigns.html', {'campaigns': successful_campaigns})


def single_sms_campaign_report(request, campaign_id):
    campaign = get_object_or_404(SMSCampaign, pk=campaign_id)
    
    # Get all users and filter the ones for this campaign
    UsersDict = User.objects.in_bulk(campaign.audience)
    all_users = list(UsersDict.values())
    users_for_campaign, campaign_interactions = users_interactions_single_campaign(all_users, campaign_id)
    extras = {
        'campaign_interactions': campaign_interactions
    }

    return render(request, 'reports/sms_campaign_report.html', 
        {'users': users_for_campaign, 'campaign': campaign, 'extras': extras})


def sms_campaign_series(request):
    parent_campaigns = SMSCampaign.objects.exclude(future_campaigns='').filter(parent_campaigns='')
    context = {
        'campaigns': parent_campaigns
    }
    return render(request, 'reports/sms_parent_campaigns.html', {'campaigns': parent_campaigns})


def single_sms_campaign_series(request, parent_campaign_id):
    parent_campaign = get_object_or_404(SMSCampaign, pk=parent_campaign_id)
    child_campaign_ids = parent_campaign.future_campaigns

    campaigns_sent = []
    campaigns_pending = []
    for id in child_campaign_ids:
        child = SMSCampaign.objects.filter(pk=id, launch_datetime__lte = timezone_now())
        if child:
            campaigns_sent.append(SMSCampaign.objects.get(pk=id))
        else:
            campaigns_pending.append(SMSCampaign.objects.get(pk=id))
    
    campaigns_sent.append(parent_campaign)
    if campaigns_sent:
        parent_campaign_user_ids = parent_campaign.audience
        parent_campaign_users = User.objects.in_bulk(parent_campaign_user_ids)
        if parent_campaign_users:
            parent_campaign_users = list(parent_campaign_users.values())

        hitrate_percentages = user_sms_hit_rates(parent_campaign_users, campaigns_sent)
        return render(request, 'reports/single_sms_campaign_series.html', {
            'hitrates': hitrate_percentages, 
            'campaign': parent_campaign, 
            'childs_sent': campaigns_sent,
            'childs_pending': campaigns_pending})
    else:
        return render(request, 'reports/null_series.html', {'childs_pending': campaigns_pending})

reports/templates/reports/audience.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Audience Report</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <u><h1><b>Audience Report: </b></h1></u>
    <br>
    <u><h3>Users and interactions</h3></u>
    <table>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>City</th>
          <th>Email Address</th>
          <th>Total Email interactions</th>
          <th>Total Link interactions</th>
          <th>Total interactions</th>
          <th>Campaign Participated</th>
        </tr>
        {% for user in users|dictsortreversed:"total_interactions" %}
            <tr>
              <td>
                <a href="{% url 'reports:single_user_report' user.id %}">
                  {{ user.name }}
                </a>
              </td> 
              <td>{{ user.location_of_interest }}</td> 
              <td>{{ user.city }}</td> 
              <td>{{ user.email }}</td>
              <td>{{ user.email_interactions }}</td>
              <td>{{ user.link_interactions }}</td>
              <td>{{ user.total_interactions }}</td>
              <td>{{ user.campaigns }}</td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/campaign_report.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Single Campaign Report</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <u><h1><b>Campaign Report for campaign: {{ campaign.name }}</b></h1></u>
    {{ campaign.description }}
    <u><h2>Demographics</h2></u>
    <p style="font-size:15px">Date created: {{ campaign.creation_date|date:'d-m-Y, H:iA' }}</p>
    <p style="font-size:15px">Users participated: {{ campaign.audience|length }}</p>
    <p style="font-size:15px">Total impressions: {{ extras.campaign_interactions }}</p>
    <br>    
    <u><h3>User Actions</h3></u>
    <table>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>City</th>
          <th>Email Address</th>
          <th>Email interactions</th>
          <th>Link interactions</th>
          <th>Total interactions</th>
        </tr>
        {% for user in users|dictsortreversed:"total_interactions" %}
            <tr>
              <td>{{ user.name }}</td> 
              <td>{{ user.location_of_interest }}</td> 
              <td>{{ user.city }}</td> 
              <td>{{ user.email }}</td>
              <td>{{ user.email_interactions }}</td>
              <td>{{ user.link_interactions }}</td>
              <td>{{ user.total_interactions }}</td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/campaigns.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Campaign Reports</title>
  </head>

  <body>
    <br><br>
    <h1>Campaign Reports</h1>
    <ul>
      {% for campaign in campaigns %}
        <li><a href="{% url 'reports:single_campaign_report' campaign.id %}">
          <b style="font-size:30px">{{ campaign.name }}</b>  
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Created on {{ campaign.creation_date|date:'d-m-Y, H:iA' }}        

        <br>
        <b style="font-size:19px"><u>Campaign Description</u></b>
        <br>{{ campaign.description }}</li>

        <br>
        <b style="font-size:19px"><u>Audience Size</u></b>
        <br>{{ campaign.audience|length }}</li>
        <br><br>
      {% endfor %}
    </ul>
  </body>
</html>

reports/templates/reports/index.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Reports</title>
  </head>

  <body>
    <br>
    <h2>Reports</h2>
    <ul>
      <li><a href="{% url 'reports:campaigns' %}">Email Campaign Status</a></li>
      <li><a href="{% url 'reports:campaign_series' %}">Email Campaign Series Report</a></li>
      <li><a href="{% url 'reports:sms_campaigns' %}">SMS Campaign Status</a></li>
      <li><a href="{% url 'reports:sms_campaign_series' %}">SMS Campaign Series Report</a></li>
      <li><a href="{% url 'reports:audience' %}">Audience / Users Status</a></li>
      <li><a href="{% url 'reports:micromarkets' %}">Micromarkets Status</a></li>      
    </ul>
  </body>
</html>

reports/templates/reports/micromarkets.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Micromarkets</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <h1>Report for Micromarkets</h1>
    <b><u>Cities</u></b>
    <ul>
        {% for k, v in cities.items %}
            <li>{{ k }}: Impressions = {{ v }}</li>
        {% endfor %}
    </ul>

    <br>
    <b><u>Sub regions</u></b>
    <table>
        <tr>
          <th>Subregion</th>
          <th>City</th>
          <th>Total interactions</th>
        </tr>
        {% for subregion in subregions|dictsortreversed:"impressions" %}
            <tr>
              <td>
                <a href="{% url 'reports:single_micromarket' subregion.subregion %}">
                  {{ subregion.subregion }}
                </a>
              </td>
              <td>{{ subregion.city }}</td> 
              <td>{{ subregion.impressions }}</td> 
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/null_series.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Parent Campaign Reports</title>
  </head>

  <body>
    <br><br>
    <h1>Parent Campaign Reports</h1>
    <h2>None of the campaigns have been triggered yet</h2>
    <h3>Campaigns pending</h3>
    <ul>
        {% for child in childs_pending %}
            <li>{{ child.name }} scheduled for {{ child.launch_datetime|date:'d-m-Y, H:iA' }}</li>
        {% endfor %}
    </ul>
  </body>
</html>

reports/templates/reports/parent_campaigns.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Parent Campaign Reports</title>
  </head>

  <body>
    <br><br>
    <h1>Campaign Reports</h1>
    <ul>
      {% for campaign in campaigns %}
        <li><a href="{% url 'reports:single_campaign_series' campaign.id %}">
          <b style="font-size:30px">{{ campaign.name }}</b>  
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Created on {{ campaign.creation_date|date:'d-m-Y, H:iA' }}        

        <br>
        <b style="font-size:19px"><u>Campaign Description</u></b>
        <br>{{ campaign.description }}</li>

        <br>
        <b style="font-size:19px"><u>Audience Size</u></b>
        <br>{{ campaign.audience|length }}</li>
        <br><br>
      {% endfor %}
    </ul>
  </body>
</html>

reports/templates/reports/single_campaign_series.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Single Campaign Series Report</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <u><h1><b>Report for campaign series: {{ campaign.name }}</b></h1></u>
    {{ campaign.description }}
    <u><h2>Automatic scheduled campaigns: </h2></u>
    <h3>Campaigns sent</h3>
    <ul>
        {% for child in childs_sent %}
            <li>{{ child.name }} sent on {{ child.launch_datetime|date:'d-m-Y, H:iA' }} for {{ child.audience|length }} people</li>
        {% endfor %}
    </ul>
    <h3>Campaigns pending</h3>
    <ul>
        {% for child in childs_pending %}
            <li>{{ child.name }} scheduled for {{ child.launch_datetime|date:'d-m-Y, H:iA' }} </li>
        {% endfor %}
    </ul>
    <u><h2>Demographics</h2></u>
    <p style="font-size:15px">Date created: {{ campaign.creation_date|date:'d-m-Y, H:iA' }}</p>
    <p style="font-size:15px">Users participated: {{ campaign.audience|length }}</p>
    <br>    
    <u><h3>Top Users</h3></u>
    <table>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Email Address</th>
          <th>Success Rate</th>
        </tr>
        {% for user in hitrates|dictsortreversed:"hit_rate" %}
            <tr>
              <td>
                <a href="{% url 'reports:single_user_report' user.user_id %}">
                {{ user.name }}
                </a>
              </td>                 
              <td>{{ user.location_of_interest }}</td> 
              <td>{{ user.email }}</td>
              <td>{{ user.hit_rate }}</td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/single_location.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Audience Report</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <u><h1><b>Audience Report for {{ subregion }}: </b></h1></u>
    <br>
    <u><h3>Users and interactions</h3></u>
    <table>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>City</th>
          <th>Email Address</th>
          <th>Total Email interactions</th>
          <th>Total Link interactions</th>
          <th>Total interactions</th>
          <th>Campaign Participated</th>
        </tr>
        {% for user in users|dictsortreversed:"total_interactions" %}
            <tr>
              <td>
                <a href="{% url 'reports:single_user_report' user.id %}">
                  {{ user.name }}
                </a>
              </td> 
              <td>{{ user.location_of_interest }}</td> 
              <td>{{ user.city }}</td> 
              <td>{{ user.email }}</td>
              <td>{{ user.email_interactions }}</td>
              <td>{{ user.link_interactions }}</td>
              <td>{{ user.total_interactions }}</td>
              <td>{{ user.campaigns }}</td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/single_sms_campaign_series.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Single Campaign Series Report</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <u><h1><b>Report for campaign series: {{ campaign.name }}</b></h1></u>
    {{ campaign.description }}
    <u><h2>Automatic scheduled campaigns: </h2></u>
    <h3>Campaigns sent</h3>
    <ul>
        {% for child in childs_sent %}
            <li>{{ child.name }} sent on {{ child.launch_datetime|date:'d-m-Y, H:iA' }} for {{ child.audience|length }} people</li>
        {% endfor %}
    </ul>
    <h3>Campaigns pending</h3>
    <ul>
        {% for child in childs_pending %}
            <li>{{ child.name }} scheduled for {{ child.launch_datetime|date:'d-m-Y, H:iA' }} </li>
        {% endfor %}
    </ul>
    <u><h2>Demographics</h2></u>
    <p style="font-size:15px">Date created: {{ campaign.creation_date|date:'d-m-Y, H:iA' }}</p>
    <p style="font-size:15px">Users participated: {{ campaign.audience|length }}</p>
    <br>    
    <u><h3>Top Users</h3></u>
    <table>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Phone Number</th>
          <th>Success Rate</th>
        </tr>
        {% for user in hitrates|dictsortreversed:"hit_rate" %}
            <tr>
              <td>
                <a href="{% url 'reports:single_user_report' user.user_id %}">
                {{ user.name }}
                </a>
              </td>                 
              <td>{{ user.location_of_interest }}</td> 
              <td>{{ user.phone_number }}</td>
              <td>{{ user.hit_rate }}</td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/single_user.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Single User Reports</title>
  </head>

  <body>
    <br><br>
    <h1>Report for {{ user.name }}</h1>
    <b> Details:</b> <br>
    {{ user.city }}<br>
    {{ user.location_of_interest }}<br>

    <h3>Campaigns participated in: </h3>
    <ul>
    {% for k,v in campaigns.items %}
        <li>Campaign ID: {{ k }} <br>
            <a href="{% url 'reports:single_campaign_report' k %}">
                <b>{{ v.name }}</b>
              </a>
        </li>
        Email impressions: {{ v.email_opens }} <br>
        Link impressions: {{ v.link_opens }}
    {% endfor %}
    </ul>
  </body>
</html>

reports/templates/reports/sms_campaign_report.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Single Campaign Report</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
      </style>
  </head>

  <body>
    <br><br>
    <u><h1><b>Campaign Report for campaign: {{ campaign.name }}</b></h1></u>
    {{ campaign.description }}
    <u><h2>Demographics</h2></u>
    <p style="font-size:15px">Date created: {{ campaign.creation_date|date:'d-m-Y, H:iA' }}</p>
    <p style="font-size:15px">Users participated: {{ campaign.audience|length }}</p>
    <p style="font-size:15px">Total impressions: {{ extras.campaign_interactions }}</p>
    <br>    
    <u><h3>User Actions</h3></u>
    <table>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>City</th>
          <th>Phone Number</th>
          <th>Link interactions</th>
        </tr>
        {% for user in users|dictsortreversed:"total_interactions" %}
            <tr>
              <td>{{ user.name }}</td> 
              <td>{{ user.location_of_interest }}</td> 
              <td>{{ user.city }}</td> 
              <td>{{ user.phone_number }}</td>
              <td>{{ user.link_interactions }}</td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>

reports/templates/reports/sms_campaigns.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Campaign Reports</title>
  </head>

  <body>
    <br><br>
    <h1>Campaign Reports</h1>
    <ul>
      {% for campaign in campaigns %}
        <li><a href="{% url 'reports:single_sms_campaign_report' campaign.id %}">
          <b style="font-size:30px">{{ campaign.name }}</b>  
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Created on {{ campaign.creation_date|date:'d-m-Y, H:iA' }}        

        <br>
        <b style="font-size:19px"><u>Campaign Description</u></b>
        <br>{{ campaign.description }}</li>

        <br>
        <b style="font-size:19px"><u>Audience Size</u></b>
        <br>{{ campaign.audience|length }}</li>
        <br><br>
      {% endfor %}
    </ul>
  </body>
</html>

reports/templates/reports/sms_parent_campaigns.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Parent Campaign Reports</title>
  </head>

  <body>
    <br><br>
    <h1>Campaign Reports</h1>
    <ul>
      {% for campaign in campaigns %}
        <li><a href="{% url 'reports:single_sms_campaign_series' campaign.id %}">
          <b style="font-size:30px">{{ campaign.name }}</b>  
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Created on {{ campaign.creation_date|date:'d-m-Y, H:iA' }}        

        <br>
        <b style="font-size:19px"><u>Campaign Description</u></b>
        <br>{{ campaign.description }}</li>

        <br>
        <b style="font-size:19px"><u>Audience Size</u></b>
        <br>{{ campaign.audience|length }}</li>
        <br><br>
      {% endfor %}
    </ul>
  </body>
</html>