crmserver/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('reports/', include('reports.urls')),
    path('', include('marketingemails.urls')),
    path('marketingtexts/', include('marketingtexts.urls')),
]

marketingemails/urls.py
from django.urls import path

from . import views

app_name = 'marketingemails'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('sendmail/', views.sendmail, name='mailsent'),
    path('audience_select/', views.audience_select, name='audience_select'),
    path('image_load/<str:campaign_id>/<str:user_id>', views.image_load, name='image_load'),
    path('redirect/<str:campaign_id>/<str:user_id>', views.redirect_yor, name='redirect_to_yor'),
]

marketingtexts/urls.py
from django.urls import path

from . import views

app_name = 'marketingtexts'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('audience_select/', views.audience_select, name='audience_select'),
    path('sendsms/', views.sendsms, name='smssent'),
    # path('image_load/<str:campaign_id>/<str:user_id>', views.image_load, name='image_load'),
    # path('redirect/<str:campaign_id>/<str:user_id>', views.redirect_yor, name='redirect_to_yor'),
]

reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),

    # EMAIL REPORTS
    path('campaigns/', views.campaigns, name='campaigns'),
    path('campaigns/<str:campaign_id>', views.single_campaign_report, name='single_campaign_report'),
    path('campaign_series/', views.campaign_series, name='campaign_series'),
    path('campaign_series/<str:parent_campaign_id>', views.single_campaign_series, name='single_campaign_series'),

    # SMS REPORTS
    path('sms_campaigns/', views.sms_campaigns, name='sms_campaigns'),
    path('sms_campaigns/<str:campaign_id>', views.single_sms_campaign_report, name='single_sms_campaign_report'),
    path('sms_campaign_series/', views.sms_campaign_series, name='sms_campaign_series'),
    path('sms_campaign_series/<str:parent_campaign_id>', views.single_sms_campaign_series, name='single_sms_campaign_series'),

    # USER REPORTS
    path('audience/', views.audience, name='audience'),
    path('audience/<str:user_id>', views.single_user_view, name='single_user_report'),
    path('micromarkets/', views.micromarkets, name='micromarkets'),
    path('micromarkets/<str:subregion>', views.single_micromarket, name='single_micromarket'),
]

marketingemails/models.py
import datetime

from django.db import models
from .customModelFields import CommaSepField, HashmapField


class User(models.Model):
    '''
    User is the main entity for our application, a single user stores all the 
    relevant information about the user and the campaigns he has participated in.
    '''
    
    name = models.CharField(max_length=200)
    email_address = models.CharField(max_length=200)  
    phone_number = models.CharField(max_length=20, blank=True, null=True, default=None)
    location_of_interest = models.CharField(max_length=100, default='NULL')  
    city = models.CharField(max_length=100, default='NULL')  
    marketing_link = models.CharField(max_length=500, default='NULL')
    join_date = models.DateTimeField('date published')

    participated_campaigns = CommaSepField(blank=True)

    def __str__(self):
        return self.name


class Campaigns(models.Model):
    '''
    Future Campaigns = Campaign IDs of the campaigns scheduled for future
    Parent Campaigns = Campaign IDs of the campaigns parent campaigns that have been sent

    Campaign Types:
        ROUND1 = 1
        ROUND2 = 2
        ROUND3 = 3
        REMARKETING = 99
    '''

    name = models.CharField(max_length=200)
    description = models.TextField(max_length=20000)
    creation_date = models.DateTimeField('date published')
    audience = CommaSepField(blank=True)
    remarket_audience = CommaSepField(blank=True)
    parent_campaigns = CommaSepField(blank=True)
    future_campaigns = CommaSepField(blank=True)
    launch_datetime = models.DateTimeField('date launched', blank=True)
    campaign_type = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f"{self.name}  |  Trigger Time: {self.launch_datetime.strftime('%d, %b %Y - %I:%M%p')}"


class UserStatus(models.Model):
    '''
    User status corresponds to the activity that the user does with the campaigns that are sent to him.
    This model is related to `User` by a one-to-one mapping.
    '''


    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='user_to_status'
    )
    email_opens = HashmapField(blank=True)
    link_opens = HashmapField(blank=True)

    def __str__(self):
        return self.user.name


class AbstractScheduledJob(models.Model):
    '''
    Abstract class to instantiate any scheduled job dispatched from the application
    '''
    scheduled_timestamp: datetime.datetime = models.DateTimeField(db_index=True)
    data: str = models.TextField()

    class Meta:
        abstract = True


class ScheduledCampaign(AbstractScheduledJob):
    '''
    Scheduled campaigns store the timestamp and additional information and related to the campaign that 
    will be scheduled to future.
    '''

    campaign = models.OneToOneField(
        Campaigns,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='campaign_to_schedule_queue'
    )
    
    def __str__(self) -> str:
        return f"Campaign `{self.campaign.name}` scheduled for: {self.scheduled_timestamp.strftime('%d %b %Y - %I:%M%p')}"

marketingemails/forms.py
from django import forms

from .models import User

class UserListForm(forms.Form):
    selection = forms.BooleanField(required=True)

class UserListModelForm(forms.ModelForm):
    selection = forms.BooleanField(required=True)
    class Meta:
        model = User
        fields = ['name', 'email_address']

marketingemails/views.py
import os
from django.utils import timezone

from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.core.mail import get_connection, EmailMultiAlternatives
from django.template.loader import render_to_string
from PIL import Image

from .models import User, UserStatus, Campaigns, ScheduledCampaign
from .forms import UserListForm, UserListModelForm
from .utils import dictionary_to_str
from .lib.automatic_campaigns import schedule_future_campaign
from .lib.send_mail import send_mass_html_mail, get_mail_data


def index(request):
    return render(request, 'marketingemails/index.html')


def create(request):
    '''
    Renders basic form to create a campaign and configure campaign related options.
    '''
    users = get_list_or_404(User, email_address__isnull=False)
    return render(request, 'marketingemails/create_campaign.html', {'users': users[:100]})


def sendmail(request):
    '''
    Renders the campaign success page after dispatching a campaign.
    The request recieved stores information about users selected, these users are fetched and 
    the camapaign is scheduled to be triggered.
    '''
    if request.POST.get('select_all_users'):
        user_pkids = list(User.objects.filter(email_address__isnull=False).exclude(email_address='').values_list('id', flat=True))
    elif request.POST.get('start_idx', None) or request.POST.get('last_idx', None):
        start_idx = int(request.POST.get('start_idx'))
        last_idx = int(request.POST.get('last_idx'))
        user_pkids = list(User.objects.filter(email_address__isnull=False).exclude(email_address='').values_list('id', flat=True))

        if last_idx <= start_idx or last_idx > len(user_pkids) or start_idx >= len(user_pkids) or len(user_pkids) == 0:
            return HttpResponseBadRequest('Index was not properly specified. Try Again')
        else:
            user_pkids = user_pkids[start_idx:last_idx]
    else:
        user_pkids = request.POST.getlist('user_selected')
    
    # Save selected audience to the campaign
    campaign_id = request.session['campaign_id']
    future_campaigns_count = request.session['future_campaigns_count']

    campaign = get_object_or_404(Campaigns, pk=campaign_id)
    campaign.audience = user_pkids
    campaign.save()

    # Add dummy future campaigns and queue them to be sent
    schedule_future_campaign(future_campaigns_count, user_pkids, campaign, 'emails')
    scheduled_current_campaign = ScheduledCampaign(
        scheduled_timestamp = timezone.now(),
        campaign=campaign
    )
    scheduled_current_campaign.save()

    return render(request, 'marketingemails/testmailsent.html')


def audience_select(request):
    '''
    Save the campaign and select audience for the same.    
    '''
    campaign = Campaigns(
        name = request.POST.get('campaign_name'),
        description = request.POST.get('campaign_desc'),
        creation_date = timezone.now(),
        launch_datetime = timezone.now()
    )
    campaign.save()
    request.session['campaign_id'] = str(campaign.id)
    request.session['future_campaigns_count'] = request.POST.get('auto_campaigns_count')
    
    users = User.objects.filter(email_address__isnull=False).exclude(email_address='')
    return render(request, 'marketingemails/audience_select.html', 
        {'users': users[:100], 'campaign': campaign, 'valid_users': len(users)})


def image_load(request, campaign_id, user_id):
    '''
    `image_load` view is responsible for validating if an email is opened 
    or not, as soon as the URI for this view is called, the entry in our 
    database is updated and a single 1x1 pixel is sent to the email as a 
    PNG image response. If the image is loaded it signifies that the user
    has opened the email.

    Input: 
    campaign_id: Campaign for which the user has opened the email
    user_id: The user who has opened the email
    '''    
    user = get_object_or_404(UserStatus, pk=user_id)
    if user.email_opens.get(campaign_id, None):
        user.email_opens[campaign_id] += 1
    else:
        user.email_opens[campaign_id] = 1
    user.save()

    # Single pixel for email open flag
    print("\nImage Loaded\n")    
    red = Image.new('RGB', (1, 1))
    response = HttpResponse(content_type="image/png")
    red.save(response, "PNG")
    
    return response


def redirect_yor(request, campaign_id, user_id):
    '''
    Takes as input the embed link sent to user in the
    email, when the user clicks that link it is registered
    here and then the user is redirected to the desired link.

    Input: 
    campaign_id: Campaign for which the user has opened the email
    user_id: The user who has opened the email
    '''
    user = get_object_or_404(UserStatus, pk=user_id)
    if user.link_opens.get(campaign_id, None):
        user.link_opens[campaign_id] += 1
    else:
        user.link_opens[campaign_id] = 1
    user.save()

    redirect_url = user.user.marketing_link
    return redirect(redirect_url)

marketingemails/templates/marketingemails/audience_select.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Audience View</title>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      <br>
      <h3> Select audience for {{ campaign.name }}  </h3>
      <form action="{% url 'marketingemails:mailsent' %}" method="post">
        {% csrf_token %}
        <h4>Send campaigns based on user index - </h4>
        This campaign will be sent out to users from the start index number to end index number (both inclusive)
        <br><br>
        <label for='start_idx'>Start index:</label><br>
        <input type="number" id="start_idx" name="start_idx" min="1"><br>
        <label for='last_idx'>Last index:</label><br>
        <input type="number" id="last_idx" name="last_idx" min="1"><br>
        Total eligible users present in database = <b>{{ valid_users }}</b>
        <br>
        Please use proper last index number within this bound to avoid errors.

        <br><br>
        <h4>Send campaigns to every eligible user in the database - </h4>
        <input type="checkbox" id="select_all_users" name="select_all_users" value="1">
        <label for="select_all_users">Send to every user </label>
        <br><br>

        <h4>Send campaigns to individual users - </h4>
        <table>
          <tr>
            <th>Selected</th>
            <th>Name</th>
            <th>Email Address</th>
            <th>Location</th>
          </tr>
          {% for user in users %}
              <tr>
                <td>
                  <input type="checkbox" id="choice{{ forloop.counter }}" name="user_selected" value="{{ user.id }}">
                  <label for="choice{{ forloop.counter }}"></label>
                </td>
                <td>{{ user.name }}</td> 
                <td>{{ user.email_address }}</td>
                <td>{{ user.location_of_interest }}</td>
              </tr>
          {% endfor %}
        </table>
        <br>
        <input type="submit" value="Start Campaign">
      </form>        
  </body>
</html>

marketingemails/templates/marketingemails/create_campaign.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create a new Campaign</title>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'marketingemails:audience_select' %}" method="post">
        {% csrf_token %}        
        <br>
        <label for='campaign_name'>Campaign name:</label><br>
        <input type="text" id="campaign_name" name="campaign_name"><br>
        
        <br><br>
        <label for='campaign_desc'>Campaign description:</label><br>
        <textarea name="campaign_desc" style="width:600px; height:300px;" 
        placeholder="A short description on what the campaign is for"></textarea><br>    

        <br><br>
        <label for='auto_campaigns_count'>Automatic subsequent campaigns :</label><br>
        <select name="auto_campaigns_count">
          <option value="0">0</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
        </select>
        
        <br><br><br>Save campaign and move to audience select<br>
        <input type="submit" value="Save campaign">  
      </form>        
  </body>
</html>

marketingemails/templates/marketingemails/index.html
<html>
  <head>
    <meta charset="utf-8">
    <title>YOR CRM</title>
  </head>

  <body>
    <br>
    <h2>CRM server</h2>
    <ul>
      <li><a href="{% url 'marketingemails:create' %}">Create EMAIL campaign</a></li>
      <li><a href="{% url 'marketingtexts:create' %}">Create SMS campaign</a></li>
      <li><a href="{% url 'reports:index' %}">Reports / Progress</a></li>
    </ul>
  </body>
</html>

marketingemails/templates/marketingemails/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Audience View</title>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'marketingemails:mailsent' %}" method="post">
        {% csrf_token %}
        <input type="checkbox" id="1" name="user_selected" value="one">
        <label for="1">Option 1</label>
        <input type="checkbox" id="2" name="user_selected" value="two">
        <label for="1">Option 2</label>
        <input type="checkbox" id="3" name="user_selected" value="three">
        <label for="1">Option 3</label>
        <input type="submit" value="Send Test Mail">
      </form>        
  </body>
</html>

marketingemails/templates/marketingemails/testmailsent.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sent!</title>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      {% csrf_token %}
      OK Done<br><br>
      
      <a href="{% url 'marketingemails:index' %}">HOME</a>
  </body>
</html>