crmserver/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('reports/', include('reports.urls')),
    path('', include('marketingemails.urls')),
    path('marketingtexts/', include('marketingtexts.urls')),
]

marketingemails/urls.py
from django.urls import path

from . import views

app_name = 'marketingemails'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('sendmail/', views.sendmail, name='mailsent'),
    path('audience_select/', views.audience_select, name='audience_select'),
    path('image_load/<str:campaign_id>/<str:user_id>', views.image_load, name='image_load'),
    path('redirect/<str:campaign_id>/<str:user_id>', views.redirect_yor, name='redirect_to_yor'),
]

marketingtexts/urls.py
from django.urls import path

from . import views

app_name = 'marketingtexts'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('audience_select/', views.audience_select, name='audience_select'),
    path('sendsms/', views.sendsms, name='smssent'),
    # path('image_load/<str:campaign_id>/<str:user_id>', views.image_load, name='image_load'),
    # path('redirect/<str:campaign_id>/<str:user_id>', views.redirect_yor, name='redirect_to_yor'),
]

reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),

    # EMAIL REPORTS
    path('campaigns/', views.campaigns, name='campaigns'),
    path('campaigns/<str:campaign_id>', views.single_campaign_report, name='single_campaign_report'),
    path('campaign_series/', views.campaign_series, name='campaign_series'),
    path('campaign_series/<str:parent_campaign_id>', views.single_campaign_series, name='single_campaign_series'),

    # SMS REPORTS
    path('sms_campaigns/', views.sms_campaigns, name='sms_campaigns'),
    path('sms_campaigns/<str:campaign_id>', views.single_sms_campaign_report, name='single_sms_campaign_report'),
    path('sms_campaign_series/', views.sms_campaign_series, name='sms_campaign_series'),
    path('sms_campaign_series/<str:parent_campaign_id>', views.single_sms_campaign_series, name='single_sms_campaign_series'),

    # USER REPORTS
    path('audience/', views.audience, name='audience'),
    path('audience/<str:user_id>', views.single_user_view, name='single_user_report'),
    path('micromarkets/', views.micromarkets, name='micromarkets'),
    path('micromarkets/<str:subregion>', views.single_micromarket, name='single_micromarket'),
]

marketingtexts/models.py
from django.db import models

from marketingemails.customModelFields import CommaSepField, HashmapField
from marketingemails.models import AbstractScheduledJob


class SMSCampaign(models.Model): 
    '''
    This model is analogous to the Campaign model from the email campaigns
    '''
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=20000)
    creation_date = models.DateTimeField('date published')
    audience = CommaSepField(blank=True)
    remarket_audience = CommaSepField(blank=True)
    parent_campaigns = CommaSepField(blank=True)
    future_campaigns = CommaSepField(blank=True)
    launch_datetime = models.DateTimeField('date launched', blank=True)
    campaign_type = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f"{self.name}  |  Trigger Time: {self.launch_datetime.strftime('%d, %b %Y - %I:%M%p')}"


class ScheduledSMSCampaign(AbstractScheduledJob):
    '''
    Scheduled SMS job for the SMS campaigns
    '''
    campaign = models.OneToOneField(
        SMSCampaign,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='campaign_to_schedule_queue'
    )

    def __str__(self) -> str:
        return f"Campaign `{self.campaign.name}` scheduled for: {self.scheduled_timestamp.strftime('%d %b %Y - %I:%M%p')}"

marketingtexts/views.py
import os
from django.utils import timezone

from django.urls import reverse
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.core.mail import get_connection, EmailMultiAlternatives
from django.template.loader import render_to_string
from PIL import Image

from marketingemails.models import User, UserStatus
from marketingemails.forms import UserListForm, UserListModelForm
from marketingemails.utils import dictionary_to_str
from marketingemails.lib.automatic_campaigns import schedule_future_campaign
from marketingemails.lib.send_mail import send_mass_html_mail, get_mail_data
from marketingemails.lib.send_sms import update_user_status

from .models import SMSCampaign, ScheduledSMSCampaign


def create(request):
    users = get_list_or_404(User, phone_number__isnull=False)
    return render(request, 'marketingtexts/create_sms_campaign.html', {'users': users[:100]})


def audience_select(request):
    '''
    Save the campaign and select audience for the same.
    '''
    campaign = SMSCampaign(
        name = request.POST.get('campaign_name'),
        description = request.POST.get('campaign_desc'),
        creation_date = timezone.now(),
        launch_datetime = timezone.now()
    )
    campaign.save()
    request.session['campaign_id'] = str(campaign.id)
    request.session['future_campaigns_count'] = request.POST.get('auto_campaigns_count')    

    users = User.objects.filter(phone_number__isnull=False).exclude(phone_number='')
    return render(request, 'marketingtexts/audience_select.html', 
        {'users': users[:100], 'campaign': campaign, 'valid_users': len(users)})


def sendsms(request):
    if request.POST.get('select_all_users'):
        user_pkids = list(User.objects.filter(phone_number__isnull=False).exclude(phone_number='').values_list('id', flat=True))
    elif request.POST.get('start_idx', None) or request.POST.get('last_idx', None):
        start_idx = int(request.POST.get('start_idx'))
        last_idx = int(request.POST.get('last_idx'))
        user_pkids = list(User.objects.filter(phone_number__isnull=False).exclude(phone_number='').values_list('id', flat=True))

        if last_idx <= start_idx or last_idx > len(user_pkids) or start_idx >= len(user_pkids) or len(user_pkids) == 0:
            return HttpResponseBadRequest('Index was not properly specified. Try Again')
        else:
            user_pkids = user_pkids[start_idx:last_idx]
    else:
        user_pkids = request.POST.getlist('user_selected')
    
    # Save selected audience to the campaign
    campaign_id = request.session['campaign_id']
    future_campaigns_count = request.session['future_campaigns_count']

    campaign = get_object_or_404(SMSCampaign, pk=campaign_id)
    campaign.audience = user_pkids
    campaign.save()

    # Add dummy future campaigns and queue them to be sent
    schedule_future_campaign(future_campaigns_count, user_pkids, campaign, 'sms')
    scheduled_current_campaign = ScheduledSMSCampaign(
        scheduled_timestamp = timezone.now(),
        campaign = campaign
    )
    scheduled_current_campaign.save()
    
    return render(request, 'marketingtexts/smssent.html')

marketingtexts/templates/marketingtexts/audience_select.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Audience View</title>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      <br>
      <h2> Select audience for {{ campaign.name }}  </h2>
      <form action="{% url 'marketingtexts:smssent' %}" method="post">
        {% csrf_token %}
        <h4>Send campaigns based on user index - </h4>
        This campaign will be sent out to users from the start index number to end index number (both inclusive)
        <br><br>
        <label for='start_idx'>Start index:</label><br>
        <input type="number" id="start_idx" name="start_idx" min="1"><br>
        <label for='last_idx'>Last index:</label><br>
        <input type="number" id="last_idx" name="last_idx" min="1"><br>
        Total eligible users present in database = <b>{{ valid_users }}</b>
        <br>
        Please use proper last index number within this bound to avoid errors.

        <br><br>
        <h4>Send campaigns to every eligible user in the database - </h4>
        <input type="checkbox" id="select_all_users" name="select_all_users" value="1">
        <label for="select_all_users">Send to every user </label>
        <br><br>

        <h4>Send campaigns to individual users - </h4>
        <table>
          <tr>
            <th>Selected</th>
            <th>Name</th>
            <th>Phone number</th>
            <th>Location</th>
          </tr>
          {% for user in users %}
              <tr>
                <td>
                  <input type="checkbox" id="choice{{ forloop.counter }}" name="user_selected" value="{{ user.id }}">
                  <label for="choice{{ forloop.counter }}"></label>
                </td>
                <td>{{ user.name }}</td> 
                <td>{{ user.phone_number }}</td>
                <td>{{ user.location_of_interest }}</td>
              </tr>
          {% endfor %}
        </table>
        <br>
        <input type="submit" value="Start Campaign">
      </form>        
  </body>
</html>

marketingtexts/templates/marketingtexts/create_sms_campaign.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create a new SMS Campaign</title>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'marketingtexts:audience_select' %}" method="post">
        {% csrf_token %}        
        <br>
        <label for='campaign_name'>Campaign name:</label><br>
        <input type="text" id="campaign_name" name="campaign_name"><br>
        
        <br><br>
        <label for='campaign_desc'>Campaign description:</label><br>
        <textarea name="campaign_desc" style="width:600px; height:300px;" 
        placeholder="A short description on what the campaign is for"></textarea><br>

        <br><br>
        <label for='auto_campaigns_count'>Automatic subsequent campaigns :</label><br>
        <select name="auto_campaigns_count">
          <option value="0">0</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
        </select>
        
        <br><br><br>Save campaign and move to audience select<br>
        <input type="submit" value="Save campaign">  
      </form>        
  </body>
</html>

marketingtexts/templates/marketingtexts/smssent.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sent!</title>
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      {% csrf_token %}
      OK Done<br><br>
      
      <a href="{% url 'marketingemails:index' %}">HOME</a>
  </body>
</html>